CREATE TABLE permissions 
	( 
		id SERIAL NOT NULL PRIMARY KEY, 
		role varchar(255) NOT NULL, 
		description varchar(255), 
		created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
		updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
		deleted_at TIMESTAMP WITH TIME ZONE
	);