#!/bin/sh
STAGED_GO_FILES=$(git diff --cached --name-only | grep ".go$")

if [ "$STAGED_GO_FILES" = "" ]; then
    exit 0
fi

PASS=true

for FILE in $STAGED_GO_FILES
do
    go test ./src/... -cover -coverprofile=c.out && go tool cover -html=c.out -o coverage.html

    ~/.asdf/installs/golang/1.15.2/packages/bin/mockgen -w $FILE
done

if ! $PASS; then
  printf "\033[0;30m\033[41mCOMMIT FAILED\033[0m\n"
  exit 1
else
  printf "\033[0;30m\033[42mCOMMIT SUCCEEDED\033[0m\n"
fi
exit 0