#!/bin/sh
STAGED_GO_FILES=$(git diff --cached --name-only | grep ".go$")

if [ "$STAGED_GO_FILES" = "" ]; then
    exit 0
fi

PASS=true

for FILE in $STAGED_GO_FILES
do
    goimports -w $FILE

    go vet $FILE
    if [[ $? != 0]]; then
        PASS=false
    fi
    
done

if ! $PASS; then
  printf "\033[0;30m\033[41mCOMMIT FAILED\033[0m\n"
  exit 1
else
  printf "\033[0;30m\033[42mCOMMIT SUCCEEDED\033[0m\n"
fi
exit 0